services:
  nginx:
    build: ./requirements/nginx/
    ports:
      - "443:443"
    networks:
      - wordpress-network
    volumes:
      - website-files:/var/www/html
    restart: on-failure

  wordpress:
    build: ./requirements/wordpress/
    restart: always
    depends_on:
     - database
    networks:
     - wordpress-network
    volumes:
     - website-files:/var/www/html
    restart: on-failure
    env_file:
      - .env

  database:
    build: ./requirements/database/
    networks:
     - wordpress-network
    volumes:
     - mariadb_data:/var/lib/mysql
    restart: on-failure
    env_file:
      - .env

networks:
  wordpress-network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/squinn/data/mariadb

  website-files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/squinn/data/wordpress
