services:
  nginx:
    build: ./requirements/nginx/
    ports:
      - "443:80"
    networks:
      - wordpress-network
    volumes:
      - website-files:/var/www/html
    restart: on-failure

  wordpress:
    build: ./requirements/wordpress/
    restart: always
    depends_on:
     - database
    networks:
     - wordpress-network
    volumes:
     - website-files:/var/www/html
    restart: on-failure
    environment:
      # データベース接続用
      WP_DATABASE_HOST: database:3306
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USER: ${WP_DATABASE_USER}
      WP_DATABASE_PASSWORD: ${WP_DATABASE_PASSWORD}
      # WordPress設定用
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER_NAME: ${WP_USER_NAME}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}

  database:
    build: ./requirements/database/
    networks:
     - wordpress-network
    volumes:
     - mariadb_data:/var/lib/mysql
    restart: on-failure

networks:
  wordpress-network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/squinn/data/mariadb

  website-files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/squinn/data/wordpress
