server {
    listen       80;
    server_name  squinn.42.fr;
    root         /var/www/html;

    location / {
        # リクエストを受けた際に提供するファイル名
        index  index.php index.html index.htm;
    }

    location ~ \.php$ {
        fastcgi_pass wordpress:9000; # wordpress is a service name
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # エラーコードが発生した際に表示するURIの指定
    # error_page   500 502 503 504  /50x.html;
    # "/50x.html"ページへ内部リダイレクト
    # location = /50x.html {
    #     root   /usr/share/nginx/html;
    # }
}

